name: First Workflow
on: workflow_dispatch # 수동 트리거 이벤트라고 함
jobs:
  first-job: # 잡이름
    runs-on: ubuntu-latest #https://docs.github.com/ko/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#%ED%94%84%EB%9D%BC%EC%9D%B4%EB%B9%97-%EB%A6%AC%ED%8F%AC%EC%A7%80%ED%86%A0%EB%A6%AC%EC%97%90-%EB%8C%80%ED%95%9C-%ED%91%9C%EC%A4%80-github-%ED%98%B8%EC%8A%A4%ED%8C%85-%EC%8B%A4%ED%96%89%EA%B8%B0
    steps:
      - name: Print greeting 
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      
  
